package com.example.trivialapp_base.model

// Definición de la clase de datos Pregunta según requisitos
data class Pregunta(
    val pregunta: String,
    val categoria: String,
    val dificultad: String, // "Facil", "Medio", "Dificil"
    val respuesta1: String,
    val respuesta2: String,
    val respuesta3: String,
    val respuesta4: String,
    val respuestaCorrecta: String // Debe coincidir con una de las anteriores
)

// Objeto para simular la base de datos local (Hardcoded)
object ProveedorPreguntas {
    fun obtenerPreguntas(): MutableList<Pregunta> {
        return mutableListOf(
            //Facil Pokémon
            Pregunta("¿Cuál es el Pokémon número 25 en la Pokédex?", "Pokemon", "Facil", "Bulbasaur", "Charmander", "Jigglypuff", "Pikachu", "Pikachu"),
            Pregunta("¿Qué tipo de Pokémon es Charmander?", "Pokemon", "Facil", "Agua", "Planta", "Eléctrico", "Fuego", "Fuego"),
            Pregunta("¿Cuál es la evolución final de Bulbasaur?", "Pokemon", "Facil", "Ivysaur", "Venusaur", "Charmander", "Gloom", "Venusaur"),
            Pregunta("¿Qué objeto se usa para atrapar Pokémon?", "Pokemon", "Facil", "Master Coin", "Safari Hat", "Pokédex", "Poké Ball", "Poké Ball"),
            Pregunta("¿Qué tipo de Pokémon es Squirtle?", "Pokemon", "Facil", "Planta", "Tierra", "Hielo", "Agua", "Agua"),
            Pregunta("¿Cómo se llama el entrenador principal del anime Pokémon?", "Pokemon", "Facil", "Red", "Brock", "Ash Ketchum", "Gary", "Ash Ketchum"),
            Pregunta("¿Cuál es la evolución de Charmander?", "Pokemon", "Facil", "Charmeleon", "Charizard", "Magmar", "Flareon", "Charmeleon"),
            Pregunta("¿Qué Pokémon acompaña a Ash desde el primer episodio?", "Pokemon", "Facil", "Bulbasaur", "Pikachu", "Squirtle", "Charmander", "Pikachu"),
            Pregunta("¿Qué tipo de Pokémon es Pikachu?", "Pokemon", "Facil", "Agua", "Eléctrico", "Normal", "Lucha", "Eléctrico"),
            Pregunta("¿Cuál es la evolución de Eevee de tipo agua?", "Pokemon", "Facil", "Vaporeon", "Jolteon", "Flareon", "Leafeon", "Vaporeon"),
            Pregunta("¿Qué Pokémon es de tipo fuego?", "Pokemon", "Facil", "Vulpix", "Poliwag", "Bellsprout", "Abra", "Vulpix"),
            Pregunta("¿Qué Pokémon puede volar?", "Pokemon", "Facil", "Pidgey", "Onix", "Squirtle", "Diglett", "Pidgey"),
            Pregunta("¿Qué tipo de Pokémon es Magikarp?", "Pokemon", "Facil", "Agua", "Normal", "Bicho", "Planta", "Agua"),
            Pregunta("¿Qué forma tiene una Poké Ball?", "Pokemon", "Facil", "Cubo", "Pirámide", "Esfera", "Cilindro", "Esfera"),
            Pregunta("¿Cuál es el Pokémon inicial de tipo fuego en Kanto?", "Pokemon", "Facil", "Vulpix", "Charmander", "Cyndaquil", "Torchic", "Charmander"),
            Pregunta("¿Qué Pokémon es conocido como el ratón eléctrico?", "Pokemon", "Facil", "Raichu", "Pichu", "Eevee", "Pikachu", "Pikachu"),
            Pregunta("¿Qué tipo de Pokémon es Bulbasaur?", "Pokemon", "Facil", "Planta/Veneno", "Agua", "Tierra", "Normal", "Planta/Veneno"),
            Pregunta("¿Qué objeto cura PS?", "Pokemon", "Facil", "Antídoto", "Revivir", "Poción", "Baya", "Poción"),
            Pregunta("¿Qué Pokémon es de tipo normal?", "Pokemon", "Facil", "Rattata", "Onix", "Geodude", "Machop", "Rattata"),
            Pregunta("¿Qué Pokémon evoluciona en Raichu?", "Pokemon", "Facil", "Pichu", "Eevee", "Pikachu", "Magnemite", "Pikachu"),

            //Facil Marvel
            Pregunta("¿Cómo se llama el martillo de Thor?", "Marvel", "Facil", "Stormbreaker", "Gungnir", "Andúril", "Mjolnir", "Mjolnir"),
            Pregunta("¿Quién es el alter ego de Iron Man?", "Marvel", "Facil", "Bruce Wayne", "Steve Rogers", "Peter Parker", "Tony Stark", "Tony Stark"),
            Pregunta("¿Qué superhéroe fue picado por una araña radioactiva?", "Marvel", "Facil", "Ant-Man", "Wolverine", "Hawkeye", "Spider-Man", "Spider-Man"),
            Pregunta("¿Qué color es la piel de Hulk?", "Marvel", "Facil", "Rojo", "Azul", "Gris", "Verde", "Verde"),
            Pregunta("¿De dónde es Black Panther?", "Marvel", "Facil", "Sokovia", "Latveria", "Genosha", "Wakanda", "Wakanda"),
            Pregunta("¿Quién es el dios del trueno?", "Marvel", "Facil", "Loki", "Thor", "Odin", "Zeus", "Thor"),
            Pregunta("¿Qué héroe usa un escudo?", "Marvel", "Facil", "Iron Man", "Hawkeye", "Captain America", "Falcon", "Captain America"),
            Pregunta("¿Qué héroe puede encogerse?", "Marvel", "Facil", "Wasp", "Hulk", "Ant-Man", "Vision", "Ant-Man"),
            Pregunta("¿Qué héroe se enfada y se transforma?", "Marvel", "Facil", "Thor", "Hulk", "Loki", "Drax", "Hulk"),
            Pregunta("¿Cuál es el nombre real de Spider-Man?", "Marvel", "Facil", "Peter Parker", "Clark Kent", "Bruce Wayne", "Tony Stark", "Peter Parker"),
            Pregunta("¿Quién dirige S.H.I.E.L.D.?", "Marvel", "Facil", "Nick Fury", "Coulson", "Maria Hill", "Pepper", "Nick Fury"),
            Pregunta("¿Qué superhéroe dice “Yo soy Groot”?", "Marvel", "Facil", "Rocket", "Thor", "Groot", "Drax", "Groot"),
            Pregunta("¿Qué vengador es un arquero?", "Marvel", "Facil", "Falcon", "Hawkeye", "Iron Man", "Star-Lord", "Hawkeye"),
            Pregunta("¿Qué héroe viene de Wakanda?", "Marvel", "Facil", "Falcon", "Blade", "Black Panther", "Luke Cage", "Black Panther"),
            Pregunta("¿Qué vengador usa magia?", "Marvel", "Facil", "Hulk", "Doctor Strange", "Iron Man", "Ant-Man", "Doctor Strange"),
            Pregunta("¿Quién es el hermano adoptivo de Thor?", "Marvel", "Facil", "Odin", "Loki", "Hela", "Baldur", "Loki"),
            Pregunta("¿Qué metal tiene el escudo del Capitán América?", "Marvel", "Facil", "Adamantium", "Vibranium", "Titanio", "Hierro", "Vibranium"),
            Pregunta("¿Qué superhéroe es un árbol?", "Marvel", "Facil", "Rocket", "Groot", "Drax", "Hulk", "Groot"),
            Pregunta("¿Quién es la Viuda Negra?", "Marvel", "Facil", "Carol Danvers", "Natasha Romanoff", "Wanda", "Pepper", "Natasha Romanoff"),
            Pregunta("¿Qué vengador es un dios?", "Marvel", "Facil", "Iron Man", "Thor", "Hawkeye", "Falcon", "Thor"),

            //Medio Pokémon
            Pregunta("¿Cuántos Pokémon originales había en la primera generación?", "Pokemon", "Medio", "100", "151", "250", "386", "151"),
            Pregunta("¿Qué Pokémon legendario representa el tiempo?", "Pokemon", "Medio", "Palkia", "Dialga", "Giratina", "Arceus", "Dialga"),
            Pregunta("¿Qué tipo es súper efectivo contra Agua?", "Pokemon", "Medio", "Fuego", "Roca", "Eléctrico", "Hielo", "Eléctrico"),
            Pregunta("¿Cuál es el Pokémon inicial de tipo planta en Hoenn?", "Pokemon", "Medio", "Chikorita", "Turtwig", "Treecko", "Bulbasaur", "Treecko"),
            Pregunta("¿Cuál es la evolución final de Squirtle?", "Pokemon", "Medio", "Wartortle", "Blastoise", "Lapras", "Feraligatr", "Blastoise"),
            Pregunta("¿Qué Pokémon es conocido como el clon de Mew?", "Pokemon", "Medio", "Ditto", "Mewtwo", "Zoroark", "Genesect", "Mewtwo"),
            Pregunta("¿Qué tipo es Gyarados?", "Pokemon", "Medio", "Agua", "Agua/Dragón", "Agua/Volador", "Dragón/Volador", "Agua/Volador"),
            Pregunta("¿Qué objeto revive a un Pokémon debilitado?", "Pokemon", "Medio", "Antídoto", "Éter", "Revivir", "Poción", "Revivir"),
            Pregunta("¿Qué tipo es súper efectivo contra Dragón?", "Pokemon", "Medio", "Planta", "Agua", "Hada", "Fuego", "Hada"),
            Pregunta("¿Qué Pokémon puede evolucionar con Piedra Trueno?", "Pokemon", "Medio", "Clefairy", "Eevee", "Pikachu", "Vulpix", "Pikachu"),
            Pregunta("¿Cuál es el Pokémon número 1 en la Pokédex?", "Pokemon", "Medio", "Bulbasaur", "Ivysaur", "Charmander", "Squirtle", "Bulbasaur"),
            Pregunta("¿Qué tipo de Pokémon es Jigglypuff?", "Pokemon", "Medio", "Normal/Hada", "Psíquico", "Fantasma", "Bicho", "Normal/Hada"),
            Pregunta("¿Qué Pokémon legendario está asociado al espacio?", "Pokemon", "Medio", "Dialga", "Rayquaza", "Mewtwo", "Palkia", "Palkia"),
            Pregunta("¿Cuál es la evolución de Snorunt con Piedra Alba?", "Pokemon", "Medio", "Glalie", "Froslass", "Gallade", "Gardevoir", "Froslass"),
            Pregunta("¿Qué Pokémon tiene la habilidad Levitación?", "Pokemon", "Medio", "Koffing", "Gastly", "Magnemite", "Diglett", "Gastly"),
            Pregunta("¿Qué movimiento puede dormir al rival?", "Pokemon", "Medio", "Descanso", "Somnífero", "Tóxico", "Rayo", "Somnífero"),
            Pregunta("¿Qué Pokémon inicial es de tipo fuego en Johto?", "Pokemon", "Medio", "Torchic", "Charmander", "Cyndaquil", "Chimchar", "Cyndaquil"),
            Pregunta("¿Qué tipo es súper efectivo contra Planta?", "Pokemon", "Medio", "Agua", "Lucha", "Fuego", "Roca", "Fuego"),
            Pregunta("¿Qué Pokémon es de tipo Hada?", "Pokemon", "Medio", "Clefairy", "Abra", "Machop", "Gastly", "Clefairy"),
            Pregunta("¿Qué Pokémon puede megaevolucionar?", "Pokemon", "Medio", "Charizard", "Dragonite", "Snorlax", "Lapras", "Charizard"),

            //Medio Marvel
            Pregunta("¿Qué gema del Infinito controla el tiempo?", "Marvel", "Medio", "Poder", "Espacio", "Realidad", "Tiempo", "Tiempo"),
            Pregunta("¿Quién es el villano principal de Infinity War?", "Marvel", "Medio", "Ultron", "Loki", "Red Skull", "Thanos", "Thanos"),
            Pregunta("¿Cómo se llama Vision antes de ser Vision?", "Marvel", "Medio", "Ultron", "Jarvis", "Friday", "Edith", "Jarvis"),
            Pregunta("¿Quién es el hermano adoptivo de Thor?", "Marvel", "Medio", "Baldur", "Hela", "Loki", "Fenrir", "Loki"),
            Pregunta("¿Qué actor interpreta a Iron Man?", "Marvel", "Medio", "Chris Evans", "Mark Ruffalo", "Robert Downey Jr.", "Chris Hemsworth", "Robert Downey Jr."),
            Pregunta("¿Cómo se llama la organización de Nick Fury?", "Marvel", "Medio", "HYDRA", "A.I.M.", "S.H.I.E.L.D.", "S.W.O.R.D.", "S.H.I.E.L.D."),
            Pregunta("¿Qué héroe controla la magia?", "Marvel", "Medio", "Wanda", "Doctor Strange", "Loki", "Vision", "Doctor Strange"),
            Pregunta("¿Cómo se llama la hermana de T’Challa?", "Marvel", "Medio", "Nakia", "Okoye", "Shuri", "Ramonda", "Shuri"),
            Pregunta("¿Qué tipo de radiación creó a Hulk?", "Marvel", "Medio", "Cósmica", "Gamma", "Ultravioleta", "X", "Gamma"),
            Pregunta("¿Qué villano fue creado por una IA de Stark?", "Marvel", "Medio", "Thanos", "Loki", "Ultron", "Red Skull", "Ultron"),
            Pregunta("¿Cómo se llama el planeta natal de Thanos?", "Marvel", "Medio", "Vormir", "Asgard", "Titan", "Knowhere", "Titan"),
            Pregunta("¿Qué actor interpreta a Doctor Strange?", "Marvel", "Medio", "Benedict Wong", "Cumberbatch", "Tom Holland", "Paul Bettany", "Cumberbatch"),
            Pregunta("¿Qué gema controla la mente?", "Marvel", "Medio", "Poder", "Tiempo", "Espacio", "Mente", "Mente"),
            Pregunta("¿Quién es el Primer Vengador?", "Marvel", "Medio", "Iron Man", "Thor", "Capitán América", "Hulk", "Capitán América"),
            Pregunta("¿Dónde se sitúa Sokovia?", "Marvel", "Medio", "Alemania", "Rusia", "País ficticio", "Polonia", "País ficticio"),
            Pregunta("¿Qué héroe es un ex neurocirujano?", "Marvel", "Medio", "Ant-Man", "Doctor Strange", "Iron Man", "Mr Fantastic", "Doctor Strange"),
            Pregunta("¿Qué vengador puede volar sin armadura?", "Marvel", "Medio", "Falcon", "Vision", "Iron Man", "Hulk", "Vision"),
            Pregunta("¿Qué héroe es también una bruja?", "Marvel", "Medio", "Scarlet Witch", "Hela", "Shuri", "Gamora", "Scarlet Witch"),
            Pregunta("¿Quién lidera normalmente a los X-Men?", "Marvel", "Medio", "Wolverine", "Tormenta", "Bestia", "Cíclope", "Cíclope"),
            Pregunta("¿Qué héroe es de Wakanda?", "Marvel", "Medio", "Falcon", "Blade", "Black Panther", "Luke Cage", "Black Panther"),

            //Dificil Pokémon
            Pregunta("¿Qué Pokémon puede aprender Transformación?", "Pokemon", "Dificil", "Mew", "Smeargle", "Ditto", "Zorua", "Ditto"),
            Pregunta("¿Cuál es el tipo dual de Lucario?", "Pokemon", "Dificil", "Lucha/Acero", "Lucha/Roca", "Acero/Psíquico", "Roca/Lucha", "Lucha/Acero"),
            Pregunta("¿Qué región se introdujo en Diamante y Perla?", "Pokemon", "Dificil", "Johto", "Unova", "Sinnoh", "Kalos", "Sinnoh"),
            Pregunta("¿Qué Pokémon tiene el número 493?", "Pokemon", "Dificil", "Giratina", "Arceus", "Darkrai", "Shaymin", "Arceus"),
            Pregunta("¿Qué habilidad copia la del rival al entrar?", "Pokemon", "Dificil", "Impostor", "Rastreo", "Adaptable", "Mutatipo", "Rastreo"),
            Pregunta("¿Qué Pokémon representa el espacio?", "Pokemon", "Dificil", "Dialga", "Giratina", "Palkia", "Arceus", "Palkia"),
            Pregunta("¿Cuál es el tipo secundario de Gardevoir?", "Pokemon", "Dificil", "Psíquico", "Hada", "Lucha", "Fantasma", "Hada"),
            Pregunta("¿Qué Pokémon cambia de forma según el clima?", "Pokemon", "Dificil", "Ditto", "Castform", "Zoroark", "Kecleon", "Castform"),
            Pregunta("¿Qué Pokémon tiene la habilidad Impostor?", "Pokemon", "Dificil", "Zorua", "Ditto", "Mimikyu", "Smeargle", "Ditto"),
            Pregunta("¿Qué región está inspirada en Francia?", "Pokemon", "Dificil", "Galar", "Unova", "Kalos", "Alola", "Kalos"),
            Pregunta("¿Qué Pokémon evoluciona con Escama Bella?", "Pokemon", "Dificil", "Feebas", "Magikarp", "Basculin", "Luvdisc", "Feebas"),
            Pregunta("¿Qué Pokémon fue el primero diseñado?", "Pokemon", "Dificil", "Pikachu", "Rhydon", "Clefairy", "Mew", "Rhydon"),
            Pregunta("¿Qué tipo es Dragapult?", "Pokemon", "Dificil", "Dragón/Fantasma", "Dragón/Siniestro", "Dragón/Volador", "Dragón/Psíquico", "Dragón/Fantasma"),
            Pregunta("¿Qué Pokémon representa el equilibrio de Hoenn?", "Pokemon", "Dificil", "Rayquaza", "Deoxys", "Regigigas", "Arceus", "Rayquaza"),
            Pregunta("¿Qué Pokémon tiene la habilidad Multitipo?", "Pokemon", "Dificil", "Silvally", "Mew", "Arceus", "Hoopa", "Arceus"),
            Pregunta("¿Qué objeto activa la megaevolución?", "Pokemon", "Dificil", "Piedra Z", "Megapiedra", "Escama Bella", "Piedra Lunar", "Megapiedra"),
            Pregunta("¿Qué Pokémon tiene número 898?", "Pokemon", "Dificil", "Zacian", "Eternatus", "Calyrex", "Zamazenta", "Calyrex"),
            Pregunta("¿Qué tipo es súper efectivo contra Fantasma?", "Pokemon", "Dificil", "Lucha", "Normal", "Siniestro", "Hada", "Siniestro"),
            Pregunta("¿Qué Pokémon legendario creó el mundo?", "Pokemon", "Dificil", "Mew", "Dialga", "Giratina", "Arceus", "Arceus"),
            Pregunta("¿Qué Pokémon es de tipo Dragón/Fantasma?", "Pokemon", "Dificil", "Dragapult", "Hydreigon", "Garchomp", "Salamence", "Dragapult"),

            //Dificil Marvel
            Pregunta("¿En qué cómic apareció Spider-Man por primera vez?", "Marvel", "Dificil", "Amazing Spider-Man #1", "Marvel Comics #1", "Amazing Fantasy #15", "Tales to Astonish #27", "Amazing Fantasy #15"),
            Pregunta("¿Qué metal compone el escudo del Capitán América?", "Marvel", "Dificil", "Adamantium", "Carbonadio", "Titanio", "Vibranium", "Vibranium"),
            Pregunta("¿Quién creó a Ultron?", "Marvel", "Dificil", "Tony Stark", "Bruce Banner", "Hank Pym", "Reed Richards", "Hank Pym"),
            Pregunta("¿Cuál es el nombre real de la Viuda Negra?", "Marvel", "Dificil", "Yelena Belova", "Maria Hill", "Natasha Romanoff", "Carol Danvers", "Natasha Romanoff"),
            Pregunta("¿Qué raza es Thanos?", "Marvel", "Dificil", "Kree", "Inhumano", "Eterno", "Asgardiano", "Eterno"),
            Pregunta("¿Quién mata a Thanos en Endgame?", "Marvel", "Dificil", "Iron Man", "Thor", "Capitán América", "Scarlet Witch", "Thor"),
            Pregunta("¿Cómo se llama el padre de Tony Stark?", "Marvel", "Dificil", "Howard Stark", "Henry Stark", "Richard Stark", "Harold Stark", "Howard Stark"),
            Pregunta("¿Qué piedra tenía el cetro de Loki?", "Marvel", "Dificil", "Espacio", "Mente", "Tiempo", "Poder", "Mente"),
            Pregunta("¿Qué arma reemplaza al Mjolnir?", "Marvel", "Dificil", "Gungnir", "Stormbreaker", "Godslayer", "Aesir", "Stormbreaker"),
            Pregunta("¿Quién hereda el escudo del Capitán América?", "Marvel", "Dificil", "Bucky Barnes", "Sam Wilson", "Nick Fury", "Peter Parker", "Sam Wilson"),
            Pregunta("¿Cuál es el verdadero nombre de Magneto?", "Marvel", "Dificil", "Max Eisenhardt", "Erik Lehnsherr", "Victor Creed", "Charles Xavier", "Erik Lehnsherr"),
            Pregunta("¿Qué entidad cósmica devora mundos?", "Marvel", "Dificil", "Dormammu", "Galactus", "Ego", "Celestial", "Galactus"),
            Pregunta("¿En qué película aparece Black Panther por primera vez?", "Marvel", "Dificil", "Black Panther", "Age of Ultron", "Civil War", "Infinity War", "Civil War"),
            Pregunta("¿Qué personaje es mitad Celestial?", "Marvel", "Dificil", "Star-Lord", "Adam Warlock", "Vision", "Captain Marvel", "Star-Lord"),
            Pregunta("¿Qué organización reemplaza a S.H.I.E.L.D.?", "Marvel", "Dificil", "HYDRA", "A.I.M.", "S.W.O.R.D.", "Roxxon", "S.W.O.R.D."),
            Pregunta("¿Cómo se llama el martillo de Beta Ray Bill?", "Marvel", "Dificil", "Mjolnir", "Stormbreaker", "Gungnir", "Aesir", "Stormbreaker"),
            Pregunta("¿Quién es el creador de Marvel junto a Kirby?", "Marvel", "Dificil", "Steve Ditko", "Stan Lee", "Bob Kane", "Joe Shuster", "Stan Lee"),
            Pregunta("¿Qué villano es el Titán Loco?", "Marvel", "Dificil", "Ultron", "Galactus", "Thanos", "Loki", "Thanos"),
            Pregunta("¿Qué gema es verde?", "Marvel", "Dificil", "Mente", "Tiempo", "Espacio", "Poder", "Tiempo"),
            Pregunta("¿Quién fundó los Vengadores?", "Marvel", "Dificil", "Nick Fury", "Iron Man", "Thor", "Capitán América", "Nick Fury"),

            //Extrema Pokemon
            Pregunta("¿Qué Pokémon ha ganado el mundial?", "Pokemon", "Extrema", "Dragonite", "Excadrill", "Pachirisu", "Calyrex Jinete Glaciar", "Pachirisu"),
            Pregunta("¿Qué acción tiene mas prioridad en el orden de turno acualmente?", "Pokemon", "Extrema", "Usar Protección", "Cambiar de Pokémon", "Usar Persecución", "Usar Refuerzo", "Cambiar de Pokémon"),
            Pregunta("¿Qué nombre icónico tiene un montañero en la Calle Victoria de Teselia?", "Pokemon", "Extrema", "Ibai", "Lionel", "Link", "Vegeta", "Ibai"),
            Pregunta("¿Qué Pokemon evoluciona a su siguiente fase por amistad?", "Pokemon", "Extrema", "Happiny", "Pawmo", "Burmy", "Swadloon", "Swadloon"),
            Pregunta("¿Qué efecto de estado no fue nerfeado, de ninguna forma, del paso de quinta a sexta generación?", "Pokemon", "Extrema", "Congelación", "Parálisis", "Confusión", "Quemaduras", "Congelación"),
            Pregunta("¿Què pokémon es originario de Hoenn?", "Pokemon", "Extrema", "Slugma", "Skarmory", "Meditite", "Burmy", "Meditite"),
            Pregunta("¿Cuál es el pokémon que ocupa la posicion 702 de la Pokédex?", "Pokemon", "Extrema", "Goomy", "Sligoo", "Dedenne", "Hawlucha", "Hawlucha"),
            Pregunta("¿Cual fue el último pokémon que evolucionó Ash, en el anime?", "Pokemon", "Extrema", "Dragonite", "Sirfetch'd", "Lucario", "Gengar", "Sirfetch'd"),
            Pregunta("¿Qué Pokémon tiene más victorias en mundiales?", "Pokemon", "Extrema", "Salamance", "Rayquaza", "Kyogre", "Garchomp", "Salamance"),
            Pregunta("¿Qué Pokémon comparte número de la pokédex nacional i estadísticas base totales?", "Pokemon", "Extrema", "Makuhita", "Metang", "Conkeldurr", "Archeops", "Archeops"),

            //Extrema Marvel
            Pregunta("¿Cuál fue el primer superhéroe en morir permanentemente en los cómics principales de Marvel?", "Marvel", "Extrema", "Captain Marvel (Mar-Vell)", "Jean Grey", "Gwen Stacy", "Vision", "Captain Marvel (Mar-Vell)"),
            Pregunta("¿En qué cómic apareció por primera vez Loki en Marvel?", "Marvel", "Extrema", "Journey Into Mystery #85", "Thor #1", "Avengers #1", "Tales to Astonish #10", "Journey Into Mystery #85"),
            Pregunta("¿Qué entidad cósmica representa la encarnación literal de la Muerte en el universo Marvel?", "Marvel", "Extrema", "Lady Death", "Oblivion", "Death", "Infinity", "Death"),
            Pregunta("¿Cómo se llama el martillo encantado que usó Thor cuando Mjolnir fue destruido en los cómics, antes de Stormbreaker?", "Marvel", "Extrema", "Jarnbjorn", "Odinblade", "Godslayer", "Thunderstrike", "Jarnbjorn"),
            Pregunta("¿Qué personaje fue el primer mutante cronológicamente nacido en la historia del universo Marvel?", "Marvel", "Extrema", "Apocalypse", "Namor", "Selene", "En Sabah Nur", "Selene"),
            Pregunta("¿Qué alias utilizó Loki cuando se hizo pasar por Odin en los cómics?", "Marvel", "Extrema", "All-Father", "Odin Borson", "Loki Allfather", "Loki Odinson", "Odin Borson"),
            Pregunta("En los cómics, ¿qué hijo de Loki se convierte en uno de los más grandes villanos asgardianos?", "Marvel", "Extrema", "Jormungand", "Fenris", "Angrboda", "Narvi", "Fenris"),
            Pregunta("¿Qué versión de Loki se convierte en ‘Kid Loki’ tras ser asesinado por Thor en Journey Into Mystery?", "Marvel", "Extrema", "Loki Laufeyson original", "Loki de la Tierra-616", "Loki de la línea temporal de Young Avengers", "Loki de los Guardianes del Tiempo", "Loki Laufeyson original"),
            Pregunta("En los cómics, Loki ha sido miembro temporal de los Vengadores bajo qué nombre?", "Marvel", "Extrema", "The Trickster", "Fandral", "Unworthy Loki", "Goblin King", "The Trickster"),
            Pregunta("¿Qué entidad cósmica manipuló a Loki para iniciar la Guerra Asgardiana en los cómics?", "Marvel", "Extrema", "Mephisto", "Dormammu", "Kang el Conquistador", "El Tribunal Viviente", "Mephisto")


            )
    }
}